# 错误处理

## 闭包处理错误的模式

### 问题一

用示例 13.3 中的编码模式通过整数除以 0 触发一个运行时 panic。

```go
package main

import (
	"fmt"
)

func division(a, b int) (ans float32) {
	defer func() {
		if err := recover(); err != nil {
			fmt.Printf("出错了 %s\r\n", err) // 出错了 runtime error: integer divide by zero
		}
	}()
	ans = float32(a / b)
	return
}

func main() {
	fmt.Println(division(1, 0))
}
```

[《go 入门指南》参考答案](https://github.com/unknwon/the-way-to-go_ZH_CN/blob/master/eBook/exercises/chapter_13/recover_divbyzero.go)